import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { sceneLinkDB } from './lib/scene-link-db.ts';
import { sceneURLs, readSceneLink } from '../src/lib/scene-links.ts';
import { SceneRepository } from '../src/lib/scene-repository.ts';
import { emptyWorkspace, makeManifest } from '../src/lib/workspace.ts';
import { sceneAssetHandler } from '../supabase/functions/scene-asset/handler.mjs';

const legacyOwner=randomUUID(),legacyScene=randomUUID();
const {db,asUser,rpc}=await sceneLinkDB(async db=>{
  await db.query('insert into auth.users values($1)',[legacyOwner]);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[legacyOwner]);
  for(const revision of [0,1])await db.query('select public.save_workspace_scene($1,$2,$3,$4,$5)',[legacyScene,'Legacy head',makeManifest(emptyWorkspace()),revision,randomUUID()]);
});
const owner=randomUUID(),other=randomUUID(),id=randomUUID(),version=randomUUID(),asset=randomUUID();
try {
  const legacy=await asUser(legacyOwner,()=>rpc('get_workspace_scene',[legacyScene,null,null]));
  assert.equal(legacy.scene.revision,2);assert.equal(legacy.scene.name,'Legacy head');
  await assert.rejects(()=>asUser(legacyOwner,()=>rpc('get_workspace_scene',[legacyScene,1,null])),/revision not found/);
  await db.query('insert into auth.users values($1),($2)',[owner,other]);
  await db.query("insert into public.assets(id,owner_id,asset_key,name,source_kind) values($1,$2,'a','Fixture','form')",[asset,owner]);
  await db.query("insert into public.asset_file_versions(id,owner_id,asset_id,fingerprint,state,files) values($1,$2,$3,'fingerprint','ready',$4)",[version,owner,asset,JSON.stringify([{name:'asset.json',size:2,sha256:'a'.repeat(64)}])]);
  const doc=makeManifest(emptyWorkspace());
  doc.instances=[{id:'instance',assetId:'a',name:'Fixture',position:[0,0,0],rotation:[0,0,0],visible:true,cloudVersionId:version}];
  const write=randomUUID();
  const first=await asUser(owner,()=>rpc('save_workspace_scene',[id,'One',doc,0,write]));
  assert.equal(first.revision_url,`/?sceneId=${id}&revision=1`);
  assert.equal((await asUser(owner,()=>rpc('save_workspace_scene',[id,'One',doc,0,write]))).revision,1);
  const newer={...doc,room:[9,6,3],instances:[]};
  await asUser(owner,()=>rpc('save_workspace_scene',[id,'Two',newer,1,randomUUID()]));
  const read=(revision:number|null,token:string|null=null)=>rpc('get_workspace_scene',[id,revision,token]);
  assert.equal((await asUser(owner,()=>read(null))).scene.revision,2);
  const pinned=await asUser(owner,()=>read(1));assert.deepEqual(pinned.scene.document,doc);assert.equal(pinned.versions[0].id,version);
  await assert.rejects(()=>asUser(owner,()=>read(99)),/revision not found/);
  await assert.rejects(()=>asUser(owner,()=>rpc('save_workspace_scene',[id,'stale',doc,1,randomUUID()])),/changed on another device/);
  await assert.rejects(()=>asUser(null,()=>read(1)),/Sign in/);
  await assert.rejects(()=>asUser(other,()=>read(1)),/access denied/);
  await assert.rejects(()=>asUser(other,()=>rpc('create_scene_share',[id,1])),/access denied/);
  await assert.rejects(()=>asUser(other,()=>rpc('revoke_scene_shares',[id])),/access denied/);
  await assert.rejects(()=>asUser(owner,()=>db.exec("update public.scene_revisions set name='tampered'")),/permission denied/);
  await assert.rejects(()=>asUser(owner,()=>db.exec('delete from public.scene_revision_assets')),/permission denied/);
  assert.equal((await asUser(other,()=>db.query('select * from public.scene_revisions'))).rows.length,0);
  await assert.rejects(()=>asUser(owner,()=>rpc('begin_asset_file_delete',[version])),/saved scene revision/);
  const share=await asUser(owner,()=>rpc('create_scene_share',[id,1]));
  const link=readSceneLink(new URL(share.url,'https://example.com'))!;
  assert.equal((await asUser(null,()=>read(1,link.token))).scene.revision,1);
  assert.equal((await asUser(other,()=>read(1,link.token))).scene.revision,1);
  await assert.rejects(()=>asUser(null,()=>read(null,link.token)),/expired, or revoked/);
  await assert.rejects(()=>asUser(null,()=>read(2,link.token)),/expired, or revoked/);
  await assert.rejects(()=>asUser(null,()=>read(1,'0'.repeat(64))),/expired, or revoked/);
  await assert.rejects(()=>asUser(null,()=>db.query('select * from public.scene_shares')),/permission denied/);
  await assert.rejects(()=>asUser(owner,()=>rpc('create_scene_share',[id,1,'2099-01-01'])),/30 days/);
  // Proxy uses the real permission RPC and only downloads referenced asset.json.
  let downloads=0;
  const handler=sceneAssetHandler({rpc:async(_name:string,args:any)=>{try{return {data:await asUser(null,()=>read(args.p_revision,args.p_share_token)),error:null};}catch{return {data:null,error:{message:'denied'}};}}},
    {from:(bucket:string)=>({download:async(path:string)=>{downloads++;assert.equal(bucket,'astra-assets');assert.equal(path,`${owner}/${version}/asset.json`);return {data:new Blob(['{}']),error:null};}})});
  const request=(versionId=version)=>new Request('https://example.com',{method:'POST',body:JSON.stringify({sceneId:id,revision:1,token:link.token,versionId})});
  assert.equal((await handler(request())).status,200);
  assert.equal((await handler(request(randomUUID()))).status,404);
  assert.equal(downloads,1);
  await asUser(owner,()=>rpc('revoke_scene_shares',[id]));
  assert.equal((await handler(request())).status,403);assert.equal(downloads,1);
  assert.equal((await asUser(owner,()=>read(1))).scene.revision,1);
  const expired=await asUser(owner,()=>rpc('create_scene_share',[id,1]));
  await db.query("update public.scene_shares set expires_at=now()-interval '1 second' where id=$1",[expired.id]);
  await assert.rejects(()=>asUser(null,()=>read(1,readSceneLink(new URL(expired.url,'https://example.com'))!.token)),/expired, or revoked/);
  const copy=await asUser(owner,()=>rpc('duplicate_workspace_scene',[id,randomUUID(),'Copy']));assert.equal(copy.revision,1);assert(copy.revision_url);
  await asUser(owner,()=>rpc('delete_workspace_scene',[id,2]));
  await assert.rejects(()=>asUser(owner,()=>read(1)),/not found or access denied/);
  await asUser(owner,()=>rpc('begin_asset_file_delete',[version]));
  await assert.rejects(()=>asUser(owner,()=>rpc('save_workspace_scene',[id,'Reused ID',newer,0,randomUUID()])),/already used/);
  assert.equal((await db.query('select * from public.scene_revisions where scene_id=$1',[id])).rows.length,0);
  const api=new SceneRepository({rpc:async(name:string,args:any)=>({data:await asUser(owner,()=>rpc(name,[args.p_id,args.p_name,args.p_document,args.p_expected_revision,args.p_write_id])),error:null})} as any,owner,false,'https://workbench.example');
  const apiScene=await api.save(emptyWorkspace(),'Agent scene',randomUUID(),0,false,()=>{});
  assert.equal(apiScene.scene.revision_url,`https://workbench.example/?sceneId=${apiScene.scene.id}&revision=1`);
  const apiUpdate=await api.save(emptyWorkspace(),'Agent update',apiScene.scene.id,1,false,()=>{});
  assert.equal(apiUpdate.scene.revision_url,`https://workbench.example/?sceneId=${apiScene.scene.id}&revision=2`);
  assert.equal(apiScene.scene.head_url,apiUpdate.scene.head_url);
  const urls=sceneURLs(id,2,'https://app.example/path');assert.equal(urls.revision_url,`https://app.example/?sceneId=${id}&revision=2`);
  for(const query of [`sceneId=bad`,`sceneId=${id}&revision=0`,`sceneId=${id}&revision=1.5`,`sceneId=${id}&revision=1e2`,`sceneId=${id}#share=${'a'.repeat(64)}`]) assert.throws(()=>readSceneLink(new URL(`https://example.com/?${query}`)),/Invalid scene link/);
  console.log('PASS PostgreSQL migrations/backfill, revision retention, head/pinned reads, owner isolation, anonymous denial, scoped sharing, expiry/revocation, geometry proxy, conflicts, idempotency, duplicate/delete, URL validation.');
} finally {await db.close();}
