import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Euler,MathUtils,Quaternion } from 'three';
import { importForm,readFormDocument } from '../src/lib/form.ts';
import { appendAssets,emptyWorkspace,evaluateWorkspace,writeKeyframe,makeManifest,readManifest,hydrateManifest,canonicalJSON } from '../src/lib/workspace.ts';
import { createWorld,applyWorldPoses } from '../src/lib/world.ts';
import { ImportService } from '../src/lib/imports.ts';
import { digestBytes } from '../src/lib/scene.ts';
import { CloudStorage } from '../src/lib/cloud-storage.ts';
import { makeAnimationFeedback } from '../src/lib/animation-feedback.ts';
import { buildSpace, inferSpaceBrief } from '../src/lib/space-builder.ts';
import { createCleanroomSamplingAnimation, createDoubledCleanroomAsset, readSamplingPlan } from '../src/lib/cleanroom.ts';
import { parseCloudBundle } from '../src/lib/cloud-storage.ts';
import { SceneRepository } from '../src/lib/scene-repository.ts';

const fixture={hardware_ir_version:'0.2',overview:{title:'Lab fixture'},assembly_metadata:{project_id:'project-1',revision:7,source_agent:'codex',api_key:'secret-fixture'},components:[{ref_des:'U1',name:'Sensor'},{ref_des:'U2',name:'Display'}],bom:[{name:'Sensor',quantity:1}],validation:{warning:[{description:'Check mounting clearance'}]},mechanical:{component_placements:[{ref_des:'U1',label:'Sensor',position:{x_mm:0,y_mm:0,z_mm:50},size:{x_mm:100,y_mm:200,z_mm:100}},{ref_des:'U2',label:'Display',position:{x_mm:200,y_mm:0,z_mm:50},size:{x_mm:100,y_mm:100,z_mm:100}}]}};
const raw=JSON.stringify(fixture);const asset=importForm(fixture,'fixture.json','digest-1');
assert.equal(asset.formProject?.revision,'7');assert.equal(asset.formProject?.projectId,'project-1');assert.equal(asset.formProject?.source,'raw_ir');assert.equal(asset.formProject?.agent,'codex');assert(!JSON.stringify(asset).includes('secret-fixture'));
let workspace=appendAssets(emptyWorkspace(),[asset,asset]);
assert.notEqual(workspace.items[0].id,workspace.items[1].id);
assert(workspace.items[1].position[0]>workspace.items[0].position[0]+asset.dimensions[0]);
workspace={...workspace,items:workspace.items.map((item,i)=>({...item,position:[i?5:2,0,0]}))};
const id=workspace.items[0].id;
for(const key of [{id:'k0',time:0,position:[2,0,0],rotation:[0,350,0]},{id:'k1',time:2,position:[4,0,0],rotation:[0,10,0]}])workspace.animation=writeKeyframe(workspace.animation,id,undefined,key as any);
workspace.animation=writeKeyframe(workspace.animation,id,asset.parts[0].id,{id:'p0',time:0,position:[0,0,0],rotation:[0,0,0]});
workspace.animation=writeKeyframe(workspace.animation,id,asset.parts[0].id,{id:'p1',time:2,position:[0,.4,0],rotation:[0,0,0]});
const pose=evaluateWorkspace(workspace.items,workspace.animation,1);
assert.equal(pose[0].position[0],3);assert.equal(pose[1].position[0],5);assert.equal(pose[0].parts[asset.parts[0].id].position[1],.2);
const q=new Quaternion().setFromEuler(new Euler(...pose[0].rotation.map(MathUtils.degToRad) as [number,number,number]));assert(Math.abs(q.w)>0.999);
assert.equal(evaluateWorkspace(workspace.items,workspace.animation,null)[0].position[0],2);
const feedback=makeAnimationFeedback(workspace,{schemaVersion:1,units:'m',upAxis:'Y',scope:'room',motion:'animation',width:480,height:480,frameCount:2,frameDelayMs:100,durationSeconds:.2,room:workspace.room,assets:[],note:'review',animation:workspace.animation,frames:[{time:0,instances:[]},{time:.1,instances:[]}]},'Raise the sensor during the final movement.');
assert.equal(feedback.format,'astra.animation-feedback');assert.equal(feedback.version,1);assert.equal(feedback.instruction,'Raise the sensor during the final movement.');assert(!JSON.stringify(feedback).includes('secret-fixture'));
assert.equal(inferSpaceBrief('I need sterile culture and cold storage'),'biofab');const demo=buildSpace('manufacturing','A compact production line');assert.equal(demo.workspace.room[0],14);assert.equal(demo.workspace.items.length,6);assert.equal(demo.workspace.animation.tracks.length,1);assert(demo.workspace.items.every(item=>item.asset.warnings[0].includes('Form OSS')));
const world=createWorld(workspace.items.map(i=>i.asset),workspace.room);applyWorldPoses(world.groups,pose);assert.equal(world.groups[0].position.x,3);world.dispose();
assert.equal(JSON.stringify(fixture),raw);
const portable=makeManifest(workspace,true);const reopened=hydrateManifest(readManifest(JSON.parse(JSON.stringify(portable))),[]);
assert.equal(canonicalJSON(makeManifest(reopened)),canonicalJSON(makeManifest(workspace)));
const missing=hydrateManifest(readManifest(makeManifest(workspace)),[]);assert(missing.items.every(i=>i.missing));
const cleanroom=await createDoubledCleanroomAsset();assert(cleanroom.dimensions.every((value,i)=>Math.abs(value-[24.384,3.04,24.384][i])<.001));assert.equal(cleanroom.source.kind,'generated');assert(cleanroom.parts.length>=5);
const samplingPlan=readSamplingPlan(JSON.parse(readFileSync('public/examples/cleanroom/sampling-plan.json','utf8')));assert.deepEqual(samplingPlan.map(room=>room.room),['A','B','C']);assert.equal(samplingPlan[1].access.status,'blocked');assert.equal(samplingPlan[1].proposedTimes.length,0);assert.throws(()=>readSamplingPlan([{room:'B',requiredSamples:2,proposedTimes:[{start:'09:00',end:'09:10'}],access:{status:'blocked',reason:'occupied'}}]),/Invalid access status/);
const cleanroomWorkspace={...appendAssets(emptyWorkspace(),[cleanroom]),room:[24.384,24.384,3.048] as [number,number,number]};
const cleanroomManifest=readManifest(JSON.parse(JSON.stringify(makeManifest(cleanroomWorkspace,true))));
const reopenedCleanroom=hydrateManifest(cleanroomManifest,[]);assert.equal(reopenedCleanroom.items.length,1);assert.equal(reopenedCleanroom.items[0].missing,false);assert.equal(reopenedCleanroom.items[0].asset.parts.length,cleanroom.parts.length);
const robotInstanceId='cleanroom-robot-fixture';const animation=createCleanroomSamplingAnimation(robotInstanceId);assert.equal(animation.loop,false);assert.equal(animation.duration,110);assert.equal(animation.tracks[0].keys.length,26);assert.deepEqual(animation.tracks[0].keys[0].position,[-3.048,.16,-7.2]);assert.notDeepEqual(animation.tracks[0].keys.at(-1)?.position,animation.tracks[0].keys[0].position);assert.deepEqual(animation.tracks[0].keys.filter(key=>[5,10,65,70].includes(key.time)).map(key=>[key.time,key.position[0],key.position[2]]),[[5,-4.2,-5.3],[10,-1.9,-5.3],[65,-4.2,5.3],[70,-1.9,5.3]]);assert(animation.tracks[0].keys.every(key=>!(key.position[0]>0&&key.position[2]<-6.096)));
const animatedManifest=structuredClone(cleanroomManifest);animatedManifest.instances.push({id:robotInstanceId,name:'Robot',assetId:cleanroom.id,position:[9.144,.16,0],rotation:[0,-90,0],visible:true});animatedManifest.animation=animation;assert.equal(hydrateManifest(readManifest(animatedManifest),[]).animation.tracks[0].instanceId,robotInstanceId);
assert.equal(parseCloudBundle(JSON.stringify({schemaVersion:1,asset:cleanroom})).asset.source.kind,'generated');
const untrustedGenerated=structuredClone(cleanroom);(untrustedGenerated.source as any).generator='unknown';
await assert.rejects(()=>new SceneRepository({} as any,'owner',false).saveMetadata([untrustedGenerated]),/provenance/);
await assert.rejects(()=>new CloudStorage({} as any,'owner').upload({id:cleanroom.id,asset:untrustedGenerated,updatedAt:Date.now()},()=>{}),/Unsupported or incomplete/);
const badGenerated=structuredClone(cleanroomManifest);delete (badGenerated.bundledAssets![0].source as any).generator;assert.throws(()=>hydrateManifest(badGenerated,[]),/Unsupported or incomplete/);
const restored=appendAssets(missing,[asset]);assert(restored.items.every(i=>!i.missing));assert.equal(restored.items[0].id,id);assert.equal(restored.items[0].position[0],2);
const invalid=structuredClone(portable);invalid.instances[0].position[0]=Infinity;assert.throws(()=>readManifest(invalid),/transform/);
const duplicate=structuredClone(fixture);duplicate.components[1].ref_des='U1';assert.throws(()=>importForm(duplicate,'bad.json','bad'),/Duplicate/);
const unknown=structuredClone(fixture);unknown.mechanical.component_placements[1].ref_des='MISSING';assert.throws(()=>importForm(unknown,'bad.json','bad'),/Unknown/);
for(const agent of ['sdk','opencode','codex']){
  const doc=readFormDocument({format:'form-project',version:1,project_id:'compiled-project',agent,project_ir:fixture,artifacts:[]},'form-project.json');assert.equal(doc.project.agent,agent);assert.equal(doc.project.revision,'7');assert.deepEqual(doc.project.ir.bom,fixture.bom);
}
const namespace={object_type:'form.project',object_id:'namespaced-project',version:9,namespaces:[{name:'project.meta',payload:{hardware_ir_version:'0.2',assembly_metadata:{source_agent:'opencode'}}},{name:'product.overview',payload:{overview:fixture.overview}},{name:'product.mech',payload:{mechanical:fixture.mechanical}},{name:'product.electrical',payload:{components:fixture.components}},{name:'product.bom',payload:{line_items:fixture.bom}},{name:'product.validation',payload:{validation:fixture.validation}},{name:'project.docs',payload:{notes:'Retained authoring details'}}]};
const namespaced=importForm(namespace,'namespace.json','namespace');assert.equal(namespaced.formProject?.revision,'9');assert.deepEqual(namespaced.formProject?.ir.validation,fixture.validation);assert.deepEqual(namespaced.formProject?.ir.bom,fixture.bom);assert.equal(namespaced.formProject?.sourceDocument?.object_type,'form.project');
const mixed=structuredClone(fixture) as any;mixed.cad_model={meshes:[{ref_des:'U1',name:'Sensor CAD',vertices:[0,0,0,100,0,0,0,100,0],faces:[0,1,2]}]};
const mixedAsset=importForm(mixed,'mixed.json','mixed');assert.equal(mixedAsset.parts.length,2);assert.equal(mixedAsset.parts[0].metadata.representation,'CAD mesh');assert.equal(mixedAsset.parts[1].metadata.ref,'U2');
const bytes=new TextEncoder().encode('STEP fixture bytes');const hash=await digestBytes(bytes.buffer);
const fakeConverter=async()=>({success:true,root:{name:'Assembly',meshes:[0],children:[]},meshes:[{name:'Sensor',attributes:{position:{array:[0,0,0,100,0,0,0,100,0]}},index:{array:[0,1,2]}}]});
const service=new ImportService(fakeConverter);const manifest={format:'form-project',version:1,project_id:'CAD-project',agent:'sdk',project_ir:{...fixture,cad_model:{path:'cad/assembly.step'}},artifacts:[{path:'cad/assembly.step',sha256:hash.toUpperCase()}]};
const imported=await service.files([new File([JSON.stringify(manifest)],'form-project.json'),new File([bytes],'assembly.step')],{upAxis:'Z',scale:1},()=>{});assert.equal(imported[0].formProject?.projectId,'CAD-project');assert.equal(imported[0].formProject?.agent,'sdk');assert.deepEqual(imported[0].formProject?.ir.validation,fixture.validation);
console.log('PASS shared instance/part transforms, rotation interpolation, immutable source, portable/missing-asset round trips, SDK/agent wrappers, namespace/BOM/validation retention, mixed geometry, and companion-CAD provenance.');
